### ISSUE TITLE
GUi scaling with hires displays

### ISSUE THREAD

**Issue by mkolar** [ynput/OpenPype#705]
**Describe the bug**
All of our GUIs don't scale correctly on high-resolution monitors. The text gets so small, that It's pretty much unusable. For me in particular it's happening on 4k 15 inch laptop. 

**To Reproduce**
Run Pype on 4k monitor and squint your eyes.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3333008/98867338-b2d15d80-246e-11eb-8178-28204d462fb2.png)

**Desktop:**
 - OS: windows

**Comment by karmakat** [comment]
Theres a whole chat about this some time ago in the discord channel. I found some good resources there. Also I use this for the moment: 

Set env var: 
QT_AUTO_SCREEN_SCALE_FACTOR = 1

Which has solved most issues on my 4k laptop screen with Pype UI.

**Comment by iLLiCiTiT** [comment]
Setting globally variable `QT_AUTO_SCREEN_SCALE_FACTOR = 1` is one possible solution.
- That has no affect in Maya. Maya's gui itself works fine but widgets don't.
- Nuke (tested v11.2v2) on the other hand does not support 4k at all, I think it is impossible to work in nuke and having 4k resolution at the same time.
    - setting the environment in Nuke makes it "closer" how it should look but breaks node graph and viewer
- not sure how that would affect other host with qt like houdini or 

# Conclusion
To "fix" tray and non-python hosts it is possible to do and it's easy (with or without the environment).
In python +qt hosts like Maya it will be harder. To fix (at least) the font size we can change `px` in stylesheets to `pt` so it should scale automatically, that requires to find out matching size and then test if it won't break style in any other hosts.

**Comment by karmakat** [comment]
[https://doc.qt.io/qt-5/highdpi.html](https://doc.qt.io/qt-5/highdpi.html)

**Comment by iLLiCiTiT** [comment]
@karmakat i know about https://doc.qt.io/qt-5/highdpi.html I've read it many times. But that's not in maya or nuke (don't know if houdini, resolve, et.c have it).

**Comment by jrsndl** [comment]
Hi,
in Nuke, the QT_AUTO_SCREEN_SCALE_FACTOR is working for 12.1 and up (win and linux, mac is special...)
I am not sure if it works with earlier versions
hth

**Comment by iLLiCiTiT** [comment]
> I am not sure if it works with earlier versions

Good to know that at least from Nuke 12 it works :) In Nuke 11 are viewer and node graph broken.

**Comment by mkolar** [comment]
`"QT_AUTO_SCREEN_SCALE_FACTOR": "1"` is working reasonably well for now. I'll leave this open on low priority for now, so we can potentially gather more problem in various hosts, but the immediate problem of pulling my hair out is solved ;)

**Comment by mkolar** [comment]
fixed for now with "QT_AUTO_SCREEN_SCALE_FACTOR": "1" variable in 3.0

**Comment by antirotor** [comment]
This is unfortunately still an issue:

![image](https://github.com/ynput/OpenPype/assets/33513211/c8826a58-641b-4ca3-8234-4fc275ef554e)

on high dpi display

![image](https://github.com/ynput/OpenPype/assets/33513211/1a8da03d-3226-4ecc-be59-a8879a17a8fd)

on "standard" HD.

**Comment by BigRoy** [comment]
@antirotor could you report what Qt version you checked with? 
And is this Windows?

Is this standalone loader? or using inside a particular host (and thus possibly using a different Qt version and/or different Qt vars from the host)

**Comment by antirotor** [comment]
This is Maya 2024 on Windows,  Qt from Maya - 5.15.2, on 3200x2000 display set with 200% scaling and 1920x1200 set with 100%

**Comment by BigRoy** [comment]
> This is Maya 2024 on Windows, Qt from Maya - 5.15.2, on 3200x2000 display set with 200% scaling and 1920x1200 set with 100%

Can you reproduce the issue in standalone loader from Tray?

**Comment by antirotor** [comment]
standalone tools like tray publisher and loader are OK, just Maya and Max so far. Nuke works fine too. We are setting:

```
QT_API: pyside2
QT_AUTO_SCREEN_SCALE_FACTOR: 1
QT_D3DCREATE_MULTITHREADED: 1
QT_ENABLE_HIGHDPI_SCALING: 0
QT_MAC_DONT_OVERRIDE_CTRL_LMB: 1
QT_PREFERRED_BINDING: PySide2
```
"vanilla" maya has just:
```
QT_D3DCREATE_MULTITHREADED: 1
QT_ENABLE_HIGHDPI_SCALING: 0
QT_MAC_DONT_OVERRIDE_CTRL_LMB: 1
```
